### ISSUE TITLE
Weekend hitlist

### ISSUE THREAD

**Issue by jimmydorry** [GetDotaStats/site#195]
Things to aim for doing, this weekend in order of priority:

- [ ] Super indexing https://github.com/GetDotaStats/site/issues/194
- [ ] Split cgv and cpv per flag https://github.com/GetDotaStats/site/issues/162
- [ ] Workshop cron improvement (missing that data, yo!) https://github.com/GetDotaStats/site/issues/190
- [ ] Time series API https://github.com/GetDotaStats/site/issues/172
- [ ] Various page overhauls (mod overview, match, recent games)

**Comment by jimmydorry** [comment]
updated

**Comment by jimmydorry** [comment]
Update

**Comment by jimmydorry** [comment]
Update

**Comment by cowsforyou** [comment]
Any updates on this jimmydorry?

**Comment by jimmydorry** [comment]
Server hardware upgrade tomorrow, then server rebuild, LAMP stack, DB and site migration, then continue with issues.

**Comment by cowsforyou** [comment]
![get em](/http://cdn.meme.am/instances/56582065.jpg)
Format: ![Alt Text](url)
