### ISSUE TITLE
Top 100 Custom Games tracking - Feature Request

### ISSUE THREAD

**Issue by jimmydorry** [GetDotaStats/site#295]
**Top 100 List page:**
- [x] GDS status of mod (accepted, pending, rejected)
- [x] Show when rank last changed
- [x] Number of days in top 10 (total)
- [x] Show how long the tracker has been running
- [x] Show highest rank achieved
- [ ] Round date to nearest whole day
- [ ] GDS level of integration (level 1, level 2, level 3)
- [ ] Add mod details (grab thumb etc.) for top 100 not currently tracked (when improving old cron, fix save location [log fail](https://l.g-ds.io/2016-11-24_13-02-01))
- [ ] Show games played this week from GDS data
- [ ] Show line graph on page for movement of top 20 games for the last month

**Mod page:**
- [ ] Graph of rank over time

**Back End:**
- [ ] Track workshop stats for mods that ever make it into the top 100
